### ISSUE TITLE
 Cannot access the administration page (Error: Can't locate Data/Parse.pm in @INC)

### ISSUE THREAD

**Issue by Phodrum** [Libki/libki-server#208] opened 2021-06-28 11:47 UTC
**Describe the bug** 

Libki-server is active (see below), but I cannot access the administration page with URL (http://ip:port/administration). 

libki.service - LSB: Start Libki at boot time
     Loaded: loaded (/etc/init.d/libki; generated)
     Active: active (running) since Mon 2021-06-28 12:07:10 BST; 3min 36s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 970 ExecStart=/etc/init.d/libki start (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 9351)
     Memory: 48.5M
     CGroup: /system.slice/libki.service
             ├─1019 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log ->
             └─2293 /home/libki/libki-server/libki.psgi

Jun 28 12:07:02 gavin-ThinkCentre-M93z systemd[1]: Starting LSB: Start Libki at boot time...
Jun 28 12:07:10 gavin-ThinkCentre-M93z libki[970]: Starting Libki...
Jun 28 12:07:10 gavin-ThinkCentre-M93z libki[976]: start_server (pid:976) starting now...
Jun 28 12:07:10 gavin-ThinkCentre-M93z libki[970]: /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/l>
Jun 28 12:07:10 gavin-ThinkCentre-M93z systemd[1]: Started LSB: Start Libki at boot time.

**Error below showing in: /var/logs/libki/libki-server.log (All my recent installations show the same error)**

starting new worker 41497
Error while loading /home/libki/libki-server/libki.psgi: Can't locate Data/Parse.pm in @INC (you may need to install the Data::Parse module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 5, <DATA> line 1662.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 5, <DATA> line 1662.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 314, <DATA> line 1662. at /home/libki/libki-server/lib/Libki.pm line 0.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4, <DATA> line 1662.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4, <DATA> line 1662.
new worker 41497 seems to have failed to start, exit status:512
starting new worker 41507

**Deployment architecture:**

•	OS: Ubuntu 20.04.1 LTS 20.04.2 LTS + Desktop and 18.04 LTS (Failing on all regardless of server installation method.)

**Desktop** 

OS: Windows
Browser: Chrome, Edge, and Firefox

**Expected behaviour**

Access admin page via a web browser session

**Background**
I have successfully installed and run several Libki test server installations over the last 12 months both on our Library Headquarters network and at home on my personal network. Our corporate ICT department have now provided me with some server space for an Ubuntu server with a view to installing Libki to be used as our PC booking system across several libraries. In the last 7 days I have performed several Libki server test installations prior to installation on our corporate server space, however all installations have the issue as described below.

Any help would l be greatly appreciated.
Thank you

**Comment by Ievaproject** [comment] 2021-06-28 16:25
Hi all, same problem with the installation. Debian 9 and 10.

Can't locate Data/Parse.pm in @INC (you may need to install the Data::Parse module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 5, <DATA> line 1662.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 5, <DATA> line 1662.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 317, <DATA> line 1662. at /usr/local/share/perl/5.24.1/Catalyst.pm line 3843, <DATA> line 1662.
	Catalyst::setup_plugins("Libki", ARRAY(0x559f21a839e8)) called at /usr/local/share/perl/5.24.1/Catalyst.pm line 1379
	Catalyst::setup("Libki") called at /home/libki/libki-server/lib/Libki.pm line 123
	require Libki.pm called at /home/libki/libki-server/installer/update_db.pl line 15
	main::BEGIN() called at /home/libki/libki-server/lib/Libki.pm line 0
	eval {...} called at /home/libki/libki-server/lib/Libki.pm line 0
Compilation failed in require at /home/libki/libki-server/installer/update_db.pl line 15, <DATA> line 1662.
BEGIN failed--compilation aborted at /home/libki/libki-server/installer/update_db.pl line 15, <DATA> line 1662.

**Comment by kylemhall** [comment] 2021-06-30 11:23
This is a bug caused by a typo. `Data::Parse` should be *`Date::Parse`*. This has been fixed in master.

**Closed** 2021-06-30 11:23 UTC
Labels: bug

**Comment by Phodrum** [comment] 2021-06-30 11:54
Thank you Kyle. My installation today worked perfectly.
