### ISSUE TITLE
Administration user gets deleted when trying to login at public page

### ISSUE THREAD

**Issue by JSahlberg** [Libki/libki-server#188] opened 2020-07-09 12:20 UTC
**Describe the bug**
If trying to login with ADMIN on the public page of Libki (../public/login) the administration account is deleted or disabled somehow. Im not able to log in to the administration part of libki anymore.
Only sollution is to create a new superuser with create_user.pl.

**To Reproduce**
1. Go to ../public/login
2. Login as your admin, will result in bad user / password
3. Try to login on the administration part... no can do...

**Expected behavior**
Well, I guess nothing should happen when trying to log in at the public part with admin

**Deployment architecture:**
 - Linux (Ubuntu server 20.04)
 - Deployment style ( LAMP )

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome and Firefox

**Comment by kylemhall** [comment] 2020-07-22 14:22
I am unable to reproduce on master. Have you tested on master yet?

**Comment by kylemhall** [comment] 2021-04-27 13:59
I think this is fixed on master. Please reopen if I'm wrong!

**Closed by kylemhall** 2021-04-27 13:59 UTC
Labels: bug
