### ISSUE TITLE
Any::Moose is deprecated. Please use Moo instead

### ISSUE THREAD

**Issue by black23** [Libki/libki-server#25] opened 2017-07-11 08:44 UTC
Docker instlation on Debian Jessie, after docker-compose exec libki perl /libki/installer/update_db.pl I got error: 
Any::Moose is deprecated. Please use Moo instead at /usr/local/lib/perl5/site_perl/5.24.1/Config/JFDI.pm line 11.
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('libki','libki',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/local/lib/perl5/site_perl/5.24.1/DBIx/Class/Storage/DBI.pm line 1517. at /libki/installer/update_db.pl line 31

**Comment by loidor** [comment] 2017-07-11 09:38
The problem isn't that Moose is deprecated. That just means it won't work in the future. 

If you read through the whole error message, you'll notice the script can't connect to the MySQL database. 

Since I've never used the Docker install, I can't really help you much on it. I did however write the manual install, so I suggest you give that one a try instead :)

**Comment by kylemhall** [comment] 2017-07-11 10:26
I'm afraid I know nothing about the Docker setup either. I was only
provided the pull request ; )

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by loidor** [comment] 2017-07-12 13:04
I'm thinking perhaps hide the Docker installation from the readme or something? Four out of seven issues (One should be closed since it's fixed, so six issues) are about the Docker installation.

**Comment by tubaclarinet** [comment] 2017-10-16 17:41
I also am having trouble with "Any::Moose is deprecated" when I run the ./installer/update_db.pl command. I followed the instructions for manual installation of Libki server found at <https://github.com/Libki/libki-server> and got that error message. There definitely seems to be something wrong in with the instructions given at that web address.

**Comment by loidor** [comment] 2017-10-17 08:42
That something is deprecated means that it won't be available in the future, but it works totally fine today. It is not an error message, but rather a warning message. 

Everything will work just fine despite that message. 

Perhaps we should add a line in there that it will appear and that you just can ignore it?

**Comment by cvarennes** [comment] 2018-02-21 14:34
I'm also having trouble with the "./installer/update_db.pl" command using the manual installation on ubuntu 16.04.3 LTS. Apart of the "Any::Moose is deprecated", the script doesn't seem to complete successfully.

Here's a screenshot of the error message in question;

![error_updatescritp](https://user-images.githubusercontent.com/36702420/36485389-1bf87aa4-16ea-11e8-9c8d-c2243d35bc8b.PNG)

Any help would be very much appreciated has we are preparing the opening of our new public librairy.

Best Regards!

**Comment by loidor** [comment] 2018-02-21 14:55
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

As said earlier in the thread, Any::Moose isn't the culprit.
Deprecated isn't an error, but a message that something will not
be available in the future. Your problem lies in DBD::mysql not
being located.

I'll do a test installation on Ubuntu to see if I get the same
problem, and if so, I'll try to work out a solution.

/Erik

cvarennes <notifications@github.com> wrote:
> I'm also having trouble with the "./installer/update_db.pl"
> command using the manual installation on ubuntu 16.04.3 LTS.
> Apart of the "Any::Moose is deprecated", the script doesn't
> seem to complete successfully.
> 
> Here's a screenshot of the error message in question;
> 
> ![error_updatescritp](https://user-images.githubusercontent.com/36702420/36485389-1bf87aa4-16ea-11e8-9c8d-c2243d35bc8b.PNG)
> 
> Any help would be very much appreciated has we are preparing
> the opening of our new public librairy.
> 
> Best Regards!
>

-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEaFmDd+ds46G9JxK65ygcSXEbd/oFAlqNiEsACgkQ5ygcSXEb
d/rI2AgAtVJmcP2cpU5wEF+au08Qf83tEtuM5nJtVSGBbcudCMjlC86Rw4iItL+J
5s31+whX70xRVhOq3tDK/9EXN9V0Ucbil4T/Da4B0S0WmPJKhPYn+NuRU62Zm92I
GBMQc7PhCa3HwhHCVGvsehWaQYOhlIOj4Wxf2OwdEM4WKO2m6lyKIQRkfuNf/MVh
REYdtsYV6SSK2GPjusmAJ7Z93XtRSWJ94EQ/TWSUbQDgQeE5rJmcV5lIRGf2uLI5
+vXXIQCf2tRnaLmwtmNnS9BmozJn/SmvXrtOtYbUy/L4hGP4l9N6EcAUHfH7N+rE
+EmFT1LGPd1iSbHilVMg0LzFTlZtZQ==
=dsrV
-----END PGP SIGNATURE-----

**Comment by cvarennes** [comment] 2018-02-21 15:01
Thank you very much for your support! It is very much appreciated!

To add more precision and for what it's worth, I use Ubuntu Server 16.04.3 LTS

Thanks again!

**Comment by loidor** [comment] 2018-02-21 17:55
Right. For some reason Ubuntu needs the package libmysqlclient-dev installed as well. Debian doesn't need it for some reason. I've made a pull request with the changes. Until Kyle merges it, it's available on https://github.com/Libki/libki-server/.

I'd suggest you reinstall Ubuntu Server first tough, in order to avoid any conflicts with the current broken install.

**Comment by cvarennes** [comment] 2018-02-21 18:53
Thank you very much for your help! I will follow your suggestion and let you know of the outcome.

Very much appreciated!

Best Regards.

**Comment by cvarennes** [comment] 2018-02-22 14:29
Good morning,

Following your suggestion, I've been able to complete the installation process without any issues.

This said, I cannot reach the web page on port 3000 from another machine on the same network. Even with the libki service running on the server.

I've read something on another thread about missing Perl module: "WWW::Form::UrlEncoded"...

I'll probably go ahead and install it to see if it solves the problem,

Thank's again!
Best Regards.

**Comment by loidor** [comment] 2018-02-22 16:42
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Sad to say, but that's something in your network. My guess is
simply that port 3000 is closed.

I just set up a Libki server running on Ubuntu Server 16.04.3 and
it runs flawlessly on port 3000.

What you could do is to edit the service file that launches
Libki, and change the port from 3000 to the default web port 80.
That should be open on pretty much any computer on any network.
You need to do this as root.

First, stop the libki service.
```
service libki stop
```

Then, edit the service file.
```
nano /etc/init.d/libki
```

Go down to line 19. Edit it so it says ```PORT="80"```.

Then, update your libki service.
```
update-rc.d libki defaults
```

And finally, start the service again.
```
service libki start
```

Hope it works out!
 
cvarennes <notifications@github.com> wrote:
> Good morning,
> 
> Following your suggestion, I've been able to complete the
> installation process without any issues.
> 
> This said, I cannot reach the web page on port 3000 from
> another machine on the same network. Even with the libki
> service running on the server.
> 
> I've read something on another thread about missing Perl
> module: "WWW::Form::UrlEncoded"...
> 
> I'll probably go ahead and install it to see if it solves the
> problem,
> 
> Thank's again!
> Best Regards.
>

-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEEaFmDd+ds46G9JxK65ygcSXEbd/oFAlqO8vwACgkQ5ygcSXEb
d/q1Ugf7BaVKIIMrVhdffXSMRrGDaDANtR6i/dR37GcBDL1zf8hhVx8VVQsx0yCr
TWsn0fVe8iTewxfbS3wGn8zmjOnrJCPgvNRjmGyB+T1Y+p+bEdS/VLZyhF8OrT0u
JiW2rxVvTBhKq93Oq3fTsWhVEsWeBYH9t6p+/WKVU+2eBGDx5qUPFy2Kuegy56uO
hJMie6z9oLnIp9ZgK8ZSuEYyxyMR8DYHD+Bvl0nLEKyeeO2+qU9lU8+qkfzluZmk
vyJWWbXhX+16WrcbUzzJCnovLzrseq2UWnphglD0tg38jsBojpERj5yCEnmrsV/4
vNm/SJlPtZRFvheILudbM9EcUz9w4w==
=Kv/N
-----END PGP SIGNATURE-----

**Comment by loidor** [comment] 2018-02-22 16:45
Apparently email comments don't support markdown, so here it is again :)

Sad to say, but that's something in your network. My guess is
simply that port 3000 is closed.

I just set up a Libki server running on Ubuntu Server 16.04.3 and
it runs flawlessly on port 3000.

What you could do is to edit the service file that launches
Libki, and change the port from 3000 to the default web port 80.
That should be open on pretty much any computer on any network.
You need to do this as root.

First, stop the libki service.
```
service libki stop
```

Then, edit the service file.
```
nano /etc/init.d/libki
```

Go down to line 19. Edit it so it says ```PORT="80"```.

Then, update your libki service.
```
update-rc.d libki defaults
```

And finally, start the service again.
```
service libki start
```

Hope it works out!

**Comment by cvarennes** [comment] 2018-02-22 21:03
Thank you very much!

Unfortunately, the problem is persisting. The web page keeps loading and loading till I close the window. No particular error message... I should have missed something somewhere, I think I will redo the whole process.

I'll keep you informed.

Best Regards

**Comment by cvarennes** [comment] 2018-02-22 21:08
Here's a screenshot of my service status.
![libki-01](https://user-images.githubusercontent.com/36702420/36564247-9fb040a6-17ea-11e8-9364-76c945301c46.PNG)

**Comment by loidor** [comment] 2018-02-22 21:42
Yeah, it looks like it's running all right.

Install Lynx, a terminal based web browser, and try to visit the page from the server itself.
```
apt-get install lynx
lynx http://192.168.196.4:3000
```
Of course, substitute my local server IP with your server's IP.

Lynx will ask you to accept cookies, so just press A and it really **should** display the web page, albeit in a crude form.

**Comment by cvarennes** [comment] 2018-02-23 13:48
Good morning,

All I get is "HTTP request sent; waiting for response."

I should have done something wrong on the server... I'll redo the whole process and keep you informed.

Thanks again! Very much appreciated!

**Comment by cvarennes** [comment] 2018-02-23 16:29
Hi, 

I have reinstalled Ubuntu + Libki and it's now working fine.

I now have problems with the timer not working. I think I've seen something somewhere about this issue.

Thanks you very much again for your support!

All the best!

**Comment by loidor** [comment] 2018-02-23 21:39
No problem :)

**Comment by loidor** [comment] 2018-02-23 21:44
Also, the timer lives in ```/home/libki/libki-server/script/cronjobs/libki.pl```. Try to run it manually, and check if that moves the timer (it should do). 

Then, run ```crontab -e``` and check that it has the two following lines:
```
* * * * *	libki	source /home/libki/.bashrc; perl -X /home/libki/libki-server/script/cronjobs/libki.pl
0 0 * * *	libki	suorce /home/libki/.bashrc; perl -X /home/libki/libki-server/script/cronjobs/libki_nightly.pl
```

The cronjob_setup.sh should've taken care of it, but yeah.

**Comment by cvarennes** [comment] 2018-02-26 18:15
The script works very well manually...

And the cronjob seems to be configured correctly. (The lines are in the configuration file).

I'm wondering if this is not a permission issue...

Thanks again, much appreciated!

**Comment by cvarennes** [comment] 2018-02-27 20:28
Hi,

The timer is still not working. I am posting a screenshot of the cron logs in case it would reveal something.

Best Regards

**Comment by cvarennes** [comment] 2018-02-27 20:28
![libki_cronjob_log](https://user-images.githubusercontent.com/36702420/36753030-e3d3ffca-1bd2-11e8-986f-bdb3ca5fe9dc.PNG)

**Comment by loidor** [comment] 2018-02-28 07:47
That's cron not being able to mail you the log. Add ```>/dev/null 2>&1``` after every line and that should go away.

Again, try to run the timer manually and see what that says.

**Comment by cvarennes** [comment] 2018-02-28 13:39
Good morning, manually, the timer runs as expected and time is decreasing.

Might it be a problem with variables? I was thinking about running the libki cronjobs by the root user instead. Would it be a good idea?

Thanks and have a great day!

**Comment by loidor** [comment] 2018-02-28 14:43
Last time we had this problem, it was because .bashrc wasn't sourced when running things through cron. That is, the local perl installation that you've done with the libki user isn't found, and cron tries to run it with the global perl installation, which doesn't contain all the things installed locally.

Can you check your crontab with ```crontab -l```? It should contain the lines 
```
* * * * *	libki	source /home/libki/.bashrc; perl -X /home/libki/libki-server/script/cronjobs/libki.pl
0 0 * * * libki suorce /home/libki/.bashrc; perl -X /home/libki/libki-server/script/cronjobs/libki_nightly.pl
```

Also, I'm not 100% sure how Ubuntu handles these things. There might be a ```.bash_profile``` which then might override ```.bashrc``` and effing things up.

Finally, for some reason I've put in the username in the cron install file, which I'm not entirely sure about why I did, since the cron running it is the libki user.

So, a couple of things to test (and please report back, so I easily can update the installation guide):

* Edit your crontab with ```crontab -e```. Remove ```libki``` from both lines.
* Check what hidden files (files starting with period) you have in your home folder. If you have a ```.bash_profile```, that _might_ be the culprit. I've never bothered learning bash config files for more than turning colour on though, so if this is the case, I'll have to do some tests first :)
* Finally, there's a really bad way to get it to work, and that's to install the perl components as root. That works, but it's imho a bad habit to install things globally "just to get it to work".

**Comment by cvarennes** [comment] 2018-02-28 16:56
OK, now reporting back;
1 - Removing "libki" from the crontab doesn't change anything.
2 - I don't have any ".bash_profile" file within the home directory. But, I have a ".profile" file. (See attached image).

![libki_home_files](https://user-images.githubusercontent.com/36702420/36800766-4e531c04-1c7e-11e8-8450-3e349e4c9d2e.PNG)

**Comment by loidor** [comment] 2018-02-28 17:00
I'll look into it and see it I can find a solution!

**Comment by loidor** [comment] 2018-03-01 14:45
Found it, but I can't get the server to run the way I want on either Ubuntu or Debian Stretch, so the manual install is again only tested on Debian Jessie. I'll solve that in the near future.

**Anyway**, a way to quick fix your timer problem is to hardcode the $PATH directories into the two cronjob scripts.

```
cd /home/libki/libki-server/script/cronjobs
nano libki.pl
```

Here, add ```use lib '/home/libki/perl5/lib/perl5';``` on a new line after ```use warnings;```.

Close and save. Open ```libki_nightly.pl``` and add the same line after ```#!/usr/bin/perl```.

**Comment by cvarennes** [comment] 2018-03-01 15:04
Well received, thank you very much again for all your support!

**Comment by cvarennes** [comment] 2018-03-01 15:27
Just confirming everything seems to be working fine with your latest suggestion.

All the best!

**Comment by loidor** [comment] 2018-03-01 16:48
Great!

The Ubuntu server keeps ruining my day - what are you using as a client?

**Comment by cvarennes** [comment] 2018-03-01 17:01
So far, for testing purposes, I was using Windows 8.1 Pro with Libki client v.2.0.1.0.

For the production environment we'll be running Windows 10 as clients. I'm going to test it very soon.

Thanks again for everything!

**Comment by loidor** [comment] 2018-03-05 19:51
Since Any::Moose is solved, I'm closing this. Please create a new issue for further problems.

**Closed by loidor** 2018-03-05 19:51 UTC
